# Generated by Django 2.2.5 on 2019-10-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
